/**
 * Copyright (c) Rui Figueira.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 */
import type { LocatorRisk } from './locatorTypes';

const dynamicRcSelectPattern = /\brc_select_\d+(?:[_-][\w-]+)?\b/i;
const nthLocatorPattern = /\.(?:nth|first|last)\s*\(/;
const xpathPattern = /(?:^|["'`])(?:xpath=|\/\/|\/html\/)/i;
const longCssPattern = /(?:^|["'`])(?:css=)?[.#\[][^\n"'`]{120,}/;

export function locatorBlacklistRisks(value?: string): LocatorRisk[] {
  if (!value)
    return [];
  const risks: LocatorRisk[] = [];
  if (dynamicRcSelectPattern.test(value)) {
    risks.push({
      severity: 'critical',
      code: 'dynamic-rc-select-id',
      reason: 'rc_select ids are generated by AntD and are not stable across renders',
      evidence: evidenceSnippet(value, dynamicRcSelectPattern),
    });
  }
  if (nthLocatorPattern.test(value)) {
    risks.push({
      severity: 'high',
      code: 'ordinal-locator',
      reason: 'ordinal locators are fragile unless scoped by business identity',
      evidence: evidenceSnippet(value, nthLocatorPattern),
    });
  }
  if (xpathPattern.test(value)) {
    risks.push({
      severity: 'high',
      code: 'xpath-locator',
      reason: 'XPath locators are DOM-structure coupled diagnostics only',
      evidence: evidenceSnippet(value, xpathPattern),
    });
  }
  if (longCssPattern.test(value)) {
    risks.push({
      severity: 'high',
      code: 'long-css-locator',
      reason: 'long CSS selectors are brittle and should not become primary business locators',
      evidence: evidenceSnippet(value, longCssPattern),
    });
  }
  return risks;
}

export function maxRiskSeverity(risks: LocatorRisk[]): LocatorRisk['severity'] {
  if (risks.some(risk => risk.severity === 'critical'))
    return 'critical';
  if (risks.some(risk => risk.severity === 'high'))
    return 'high';
  if (risks.some(risk => risk.severity === 'medium'))
    return 'medium';
  return 'low';
}

function evidenceSnippet(value: string, pattern: RegExp) {
  const match = value.match(pattern);
  const text = match?.[0] || value;
  return text.length > 80 ? `${text.slice(0, 77)}...` : text;
}
